In [1]:
%load_ext autoreload
%autoreload 2

In [3]:
from models.CLPTransformer_v6 import CLPTransformer
from training import load_model

model_name = "CLPTransformer_v6_4_CL"

model = load_model(CLPTransformer, model_name)

# Solvers

In [3]:
from solvers.greedy.greedy_model import GreedyModelSolver

instance_file = "benchmarks/BR4.txt"
instance_number = 1
w = 8
min_fr = 1

greedy_solver = GreedyModelSolver(model, w=8) # W = 8 selecciona 64 candidatos
greedy_eval = greedy_solver.solve(instance_file, instance_number, min_fr)
print(greedy_eval)

93.29706058102428

In [4]:
from solvers.greedy.vcs import VCSSolver

instance_file = "benchmarks/BR4.txt"
instance_number = 1
w = 8
min_fr = 1

vcs_solver = VCSSolver()
vcs_eval = vcs_solver.solve(instance_file, instance_number, min_fr)
print(vcs_eval)

88.959857

In [7]:
from solvers.bs.bsm_vcs import BSM_VCS_Solver

instance_file = "benchmarks/BR4.txt"
instance_number = 1
w = 8
min_fr = 1

bsm_solver = BSM_VCS_Solver(model)
bsm_eval = bsm_solver.solve(instance_file, instance_number, w, min_fr)
print(bsm_eval)

96.19752260081715

In [8]:
from solvers.timed.timed_bsm_vcs import Timed_BSM_VCS_Solver

instance_file = "benchmarks/BR4.txt"
instance_number = 1
min_fr = 1
time = 6

bsm_solver = Timed_BSM_VCS_Solver(model)
bsm_eval = bsm_solver.solve(instance_file, instance_number, min_fr, time)
print(bsm_eval)

96.39765806281369

In [3]:
from solvers.bs.bsm_gm import BSM_GM_Solver

instance_file = "benchmarks/BR4.txt"
instance_number = 1
w = 8
min_fr = 1

bsm_solver = BSM_GM_Solver(model)
bsm_eval = bsm_solver.solve(instance_file, instance_number, w, min_fr)
print(bsm_eval)

95.99465529973459

In [6]:
from solvers.timed.timed_bsm_gm import Timed_BSM_GM_Solver

instance_file = "benchmarks/BR4.txt"
instance_number = 1
min_fr = 1
time = 3

bsm_solver = Timed_BSM_GM_Solver(model)
bsm_solver.verbose = True
bsm_eval = bsm_solver.solve(instance_file, instance_number, min_fr, time)
print(bsm_eval)

Ejecutando Timed BSM-GM con w = 1
Actualizando mejor volumen: 88.95985725309924
Ejecutando Timed BSM-GM con w = 2
Actualizando mejor volumen: 93.61347534465374
Ejecutando Timed BSM-GM con w = 3
Actualizando mejor volumen: 95.16375746852236
Ejecutando Timed BSM-GM con w = 4
95.16375746852236

# Comparación

In [21]:
from solvers.evaluators.greedy_evaluator import greedy_eval
from solvers.greedy.greedy_model import GreedyModelSolver
from solvers.greedy.vcs import VCSSolver

greedy_model_solver = GreedyModelSolver(model, w=8)
vcs_solver = VCSSolver()

solver_list = [greedy_model_solver, vcs_solver]
instance_file = "benchmarks/BR7.txt"
num_instances = 100
min_fr = 1

df = greedy_eval(solver_list, instance_file, num_instances, min_fr)
display(df.head())
df.mean()

   instance  Vol GreedyModel  Time GreedyModel    Vol VCS  Time VCS
0         0        93.668528          0.126369  92.378422  0.045612
1         1        92.931091          0.142805  91.896797  0.065792
2         2        92.098857          0.137824  92.752527  0.051539
3         3        92.998699          0.167311  92.890824  0.096251
4         4        90.973748          0.126112  91.145880  0.056337

instance            49.500000
Vol GreedyModel     91.680186
Time GreedyModel     0.904889
Vol VCS             91.689704
Time VCS             0.067106
dtype: float64

In [31]:
from solvers.evaluators.bs_evaluator import bs_eval
from solvers.bs.bsm_vcs import BSM_VCS_Solver
from solvers.bs.bsm_gm import BSM_GM_Solver
from solvers.bs.bsg import BSG_Solver

bsm_vcs_solver = BSM_VCS_Solver(model)
bsm_gm_solver = BSM_GM_Solver(model)
bsg_solver = BSG_Solver()

solver_list = [bsm_vcs_solver, bsg_solver]
instance_file = "benchmarks/BR1.txt"
num_instances = 100
w = 8
min_fr = 1

df = bs_eval(solver_list, instance_file, num_instances, w, min_fr)
display(df.head())
df.mean()

   instance  Vol BSM-VCS  Time BSM-VCS    Vol BSG  Time BSG
0         0    93.560703      0.181618  93.953696  0.154901
1         1    96.279435      0.353905  95.766467  0.386617
2         2    89.594232      0.114630  88.623931  0.065756
3         3    92.103855      0.431693  92.853027  0.371426
4         4    94.625612      0.168390  94.790150  0.092164

instance        49.500000
Vol BSM-VCS     94.329463
Time BSM-VCS     0.203817
Vol BSG         94.355106
Time BSG         0.159408
dtype: float64

In [6]:
from solvers.evaluators.timed_evaluator import timed_eval
from solvers.timed.timed_bsm_vcs import Timed_BSM_VCS_Solver
from solvers.timed.timed_bsm_gm import Timed_BSM_GM_Solver
from solvers.timed.timed_bsg import Timed_BSG_Solver

bsm_vcs_solver = Timed_BSM_VCS_Solver(model)
bsg_solver = Timed_BSG_Solver()

solver_list = [bsm_vcs_solver]
instance_file = "benchmarks/BR1.txt"
num_instances = 100
start = 0
min_fr = 1
time = 150

df = timed_eval(solver_list, instance_file, num_instances, min_fr, time, start)
display(df.head())
df.mean()

   instance  Timed BSM-VCS
0         0      94.739681
1         1      97.495924
2         2      92.345742
3         3      93.399142
4         4      95.232918

instance         49.500000
Timed BSM-VCS    95.740213
dtype: float64