In [1]:
%load_ext autoreload
%autoreload 2

In [5]:
from models.CLPTransformer_v7 import CLPTransformer
from training import load_model

model_name = "CLPTransformer_v7_2_ACL"

model = load_model(CLPTransformer, model_name)

# Solvers

In [4]:
from solvers.greedy.greedy_model import GreedyModelSolver

instance_file = "benchmarks/BR8.txt"
instance_number = 1
w = 8
min_fr = 0.98

greedy_solver = GreedyModelSolver(model, w=8) # W = 8 selecciona 64 candidatos
greedy_eval, _ = greedy_solver.solve(instance_file, instance_number, min_fr)
print(greedy_eval)

91.47876244365997

In [ ]:
from solvers.greedy.vcs import VCSSolver

instance_file = "benchmarks/BR4.txt"
instance_number = 1
w = 8
min_fr = 1

vcs_solver = VCSSolver()
vcs_eval, _ = vcs_solver.solve(instance_file, instance_number, min_fr)
print(vcs_eval)

88.959857

In [4]:
from solvers.bs.bsm_vcs import BSM_VCS_Solver

instance_file = "benchmarks/BR4.txt"
instance_number = 1
w = 8
min_fr = 1

bsm_solver = BSM_VCS_Solver(model)
bsm_eval, _ = bsm_solver.solve(instance_file, instance_number, w, min_fr)
print(bsm_eval)

95.45510046321621

In [ ]:
from solvers.timed.timed_bsm_vcs import Timed_BSM_VCS_Solver

instance_file = "benchmarks/BR4.txt"
instance_number = 1
min_fr = 1
time = 6

bsm_solver = Timed_BSM_VCS_Solver(model)
bsm_eval = bsm_solver.solve(instance_file, instance_number, min_fr, time)
print(bsm_eval)

96.39765806281369

In [5]:
from solvers.bs.bsm_gm import BSM_GM_Solver

instance_file = "benchmarks/BR4.txt"
instance_number = 1
w = 8
min_fr = 1

bsm_solver = BSM_GM_Solver(model)
bsm_eval, _ = bsm_solver.solve(instance_file, instance_number, w, min_fr)
print(bsm_eval)

94.85109815278491

In [6]:
from solvers.timed.timed_bsm_gm import Timed_BSM_GM_Solver

instance_file = "benchmarks/BR4.txt"
instance_number = 1
min_fr = 1
time = 3

bsm_solver = Timed_BSM_GM_Solver(model)
bsm_solver.verbose = True
bsm_eval = bsm_solver.solve(instance_file, instance_number, min_fr, time)
print(bsm_eval)

Ejecutando Timed BSM-GM con w = 1
Actualizando mejor volumen: 88.95985725309924
Ejecutando Timed BSM-GM con w = 2
Actualizando mejor volumen: 93.61347534465374
Ejecutando Timed BSM-GM con w = 3
Actualizando mejor volumen: 95.16375746852236
Ejecutando Timed BSM-GM con w = 4
95.16375746852236

# Comparación

92.15

In [6]:
from solvers.evaluators.greedy_evaluator import greedy_eval
from solvers.greedy.greedy_model import GreedyModelSolver
from solvers.greedy.vcs import VCSSolver

greedy_model_solver = GreedyModelSolver(model, w=8)
vcs_solver = VCSSolver()

solver_list = [greedy_model_solver, vcs_solver]
instance_file = "benchmarks/BR8.txt"
num_instances = 100
min_fr = 0.98

df = greedy_eval(solver_list, instance_file, num_instances, min_fr)
display(df.head())
round(df.mean(), 2)

   instance  Vol GreedyModel  Time GreedyModel    Vol VCS  Time VCS
0         0        93.198751          0.108076  91.471242  0.037968
1         1        91.478762          0.114807  92.030149  0.025675
2         2        91.453614          0.126626  91.410078  0.022704
3         3        91.998457          0.115820  92.075337  0.038002
4         4        93.420435          0.114233  93.392243  0.023421

instance            49.50
Vol GreedyModel     92.10
Time GreedyModel     0.10
Vol VCS             91.57
Time VCS             0.02
dtype: float64

In [12]:
from solvers.evaluators.bs_evaluator import bs_eval
from solvers.bs.bsm_vcs import BSM_VCS_Solver
from solvers.bs.bsm_gm import BSM_GM_Solver
from solvers.bs.bsg import BSG_Solver

bsm_vcs_solver = BSM_VCS_Solver(model)
bsm_gm_solver = BSM_GM_Solver(model)
bsg_solver = BSG_Solver()

solver_list = [bsm_vcs_solver, bsg_solver]
instance_file = "benchmarks/BR8.txt"
num_instances = 20
w = 8
min_fr = 0.98

df = bs_eval(solver_list, instance_file, num_instances, w, min_fr)
display(df.head())
round(df.mean(), 2)

   instance  Vol BSM-VCS  Time BSM-VCS    Vol BSG  Time BSG
0         0    95.166054      8.250562  95.053351  6.616119
1         1    94.964436      5.442800  95.337475  5.832926
2         2    95.097961      4.199118  94.917825  4.389172
3         3    95.039239      6.364590  95.003795  6.827010
4         4    96.078927      6.720709  95.580938  5.657508

instance         9.50
Vol BSM-VCS     95.21
Time BSM-VCS     4.99
Vol BSG         95.06
Time BSG         4.79
dtype: float64

In [6]:
from solvers.evaluators.timed_evaluator import timed_eval
from solvers.timed.timed_bsm_vcs import Timed_BSM_VCS_Solver
from solvers.timed.timed_bsm_gm import Timed_BSM_GM_Solver
from solvers.timed.timed_bsg import Timed_BSG_Solver

bsm_vcs_solver = Timed_BSM_VCS_Solver(model)
bsg_solver = Timed_BSG_Solver()

solver_list = [bsm_vcs_solver]
instance_file = "benchmarks/BR1.txt"
num_instances = 100
start = 0
min_fr = 1
time = 150

df = timed_eval(solver_list, instance_file, num_instances, min_fr, time, start)
display(df.head())
df.mean()

   instance  Timed BSM-VCS
0         0      94.739681
1         1      97.495924
2         2      92.345742
3         3      93.399142
4         4      95.232918

instance         49.500000
Timed BSM-VCS    95.740213
dtype: float64