In [1]:
%load_ext autoreload
%autoreload 2

In [1]:
from models.CLPTransformer_v6 import CLPTransformer
from training import load_model

model_name = "CLPTransformer_v6_3_CL"

model = load_model(CLPTransformer, model_name)

# Solvers

In [3]:
from solvers.greedy.greedy_model import GreedyModelSolver

instance_file = "benchmarks/BR4.txt"
instance_number = 1
w = 8
min_fr = 1

greedy_solver = GreedyModelSolver(model, w=8) # W = 8 selecciona 64 candidatos
greedy_eval = greedy_solver.solve(instance_file, instance_number, min_fr)
print(greedy_eval)

93.29706058102428

In [4]:
from solvers.greedy.vcs import VCSSolver

instance_file = "benchmarks/BR4.txt"
instance_number = 1
w = 8
min_fr = 1

vcs_solver = VCSSolver()
vcs_eval = vcs_solver.solve(instance_file, instance_number, min_fr)
print(vcs_eval)

88.959857

In [3]:
from solvers.bs.bsm_vcs import BSM_VCS_Solver

instance_file = "benchmarks/BR4.txt"
instance_number = 1
w = 8

bsm_solver = BSM_VCS_Solver(model)
bsm_eval = bsm_solver.solve(instance_file, instance_number, w)
print(bsm_eval)

96.36807310959726

In [6]:
from solvers.timed.timed_bsm_vcs import Timed_BSM_VCS_Solver

instance_file = "benchmarks/BR4.txt"
instance_number = 1
time = 6

bsm_solver = Timed_BSM_VCS_Solver(model)
bsm_eval = bsm_solver.solve(instance_file, instance_number, time)
print(bsm_eval)

96.32415098628697

In [3]:
from solvers.bs.bsm_gm import BSM_GM_Solver

instance_file = "benchmarks/BR4.txt"
instance_number = 1
w = 8

bsm_solver = BSM_GM_Solver(model)
bsm_eval = bsm_solver.solve(instance_file, instance_number, w)
print(bsm_eval)

95.08014724014461

In [2]:
from solvers.timed.timed_bsm_gm import Timed_BSM_GM_Solver

instance_file = "benchmarks/BR4.txt"
instance_number = 1
time = 4

bsm_solver = Timed_BSM_GM_Solver(model)
bsm_solver.verbose = True
bsm_eval = bsm_solver.solve(instance_file, instance_number, time)
print(bsm_eval)

Ejecutando BSM-GM con w = 1
Actualizando mejor volumen: 92.51362097627022
Ejecutando BSM-GM con w = 2
Actualizando mejor volumen: 94.18355898146936
Ejecutando BSM-GM con w = 3
Actualizando mejor volumen: 94.38503709917241
94.38503709917241

# Comparación

In [4]:
from solvers.evaluators.greedy_evaluator import greedy_eval
from solvers.greedy.greedy_model import GreedyModelSolver
from solvers.greedy.vcs import VCSSolver
# 1.1857
#greedy_model_solver = GreedyModelSolver(model, w=8)
vcs_solver = VCSSolver()

solver_list = [vcs_solver]
instance_file = "benchmarks/BR15.txt"
num_instances = 100
min_fr = 0.98

df = greedy_eval(solver_list, instance_file, num_instances, min_fr)
display(df.head())
df.mean()

KeyboardInterrupt:

In [6]:
from solvers.evaluators.bs_evaluator import bs_eval
from solvers.bs.bsm_vcs import BSM_VCS_Solver
from solvers.bs.bsm_gm import BSM_GM_Solver
from solvers.bs.bsg import BSG_Solver

bsm_vcs_solver = BSM_VCS_Solver(model)
bsm_gm_solver = BSM_GM_Solver(model)
bsg_solver = BSG_Solver()

solver_list = [bsm_vcs_solver, bsm_gm_solver, bsg_solver]
instance_file = "benchmarks/BR4.txt"
num_instances = 5
w = 8
min_fr = 1

df = bs_eval(solver_list, instance_file, num_instances, w, min_fr)
display(df.head())
df.mean()

,instance,Vol BSM-VCS,Time BSM-VCS,Vol BSM-GM,Time BSM-GM,Vol BSG,Time BSG
0,0,95.886309,0.865192,95.319316,3.196688,95.244041,0.875613
1,1,95.557295,1.496406,95.080147,5.969260,95.968095,1.154357
2,2,96.343603,1.151368,95.465340,3.185422,95.716652,1.002609
3,3,96.815835,1.936800,95.866329,10.489192,96.496855,1.348655
4,4,95.435034,1.618461,96.241458,6.273810,95.684243,0.910386

instance         2.000000
Vol BSM-VCS     96.007615
Time BSM-VCS     1.413646
Vol BSM-GM      95.594518
Time BSM-GM      5.822874
Vol BSG         95.821977
Time BSG         1.058324
dtype: float64

In [3]:
from solvers.evaluators.timed_evaluator import timed_eval
from solvers.timed.timed_bsm_vcs import Timed_BSM_VCS_Solver
from solvers.timed.timed_bsm_gm import Timed_BSM_GM_Solver
from solvers.timed.timed_bsg import Timed_BSG_Solver

bsm_vcs_solver = Timed_BSM_VCS_Solver(model)
bsg_solver = Timed_BSG_Solver()

solver_list = [bsm_vcs_solver, bsg_solver]
instance_file = "benchmarks/BR15.txt"
num_instances = 5
start = 0
min_fr = 1
time = 30

df = timed_eval(solver_list, instance_file, num_instances, min_fr, time, start)
display(df.head())
df.mean()

   instance  Timed BSM-VCS  Timed BSG
0         0      94.516006  94.268067
1         1      93.718864  94.042703
2         2      93.304475  93.825894
3         3      93.758858  94.240329
4         4      93.568476  93.634503

instance          2.000000
Timed BSM-VCS    93.773336
Timed BSG        94.002299
dtype: float64