In [1]:
%load_ext autoreload
%autoreload 2

In [1]:
from models.CLPTransformer_v4 import CLPTransformer
from training import load_model

model_name = "CLPTransformer_v4_CL"

model = load_model(CLPTransformer, model_name)

# Solvers

In [3]:
from solvers.bs.bsm_vcs import BSM_VCS_Solver

instance_file = "benchmarks/BR4.txt"
instance_number = 1
w = 8

bsm_solver = BSM_VCS_Solver(model)
bsm_eval = bsm_solver.solve(instance_file, instance_number, w)
print(bsm_eval)

96.36807310959726

In [6]:
from solvers.timed.timed_bsm_vcs import Timed_BSM_VCS_Solver

instance_file = "benchmarks/BR4.txt"
instance_number = 1
time = 6

bsm_solver = Timed_BSM_VCS_Solver(model)
bsm_eval = bsm_solver.solve(instance_file, instance_number, time)
print(bsm_eval)

96.32415098628697

In [3]:
from solvers.bs.bsm_gm import BSM_GM_Solver

instance_file = "benchmarks/BR4.txt"
instance_number = 1
w = 8

bsm_solver = BSM_GM_Solver(model)
bsm_eval = bsm_solver.solve(instance_file, instance_number, w)
print(bsm_eval)

95.08014724014461

In [2]:
from solvers.timed.timed_bsm_gm import Timed_BSM_GM_Solver

instance_file = "benchmarks/BR4.txt"
instance_number = 1
time = 4

bsm_solver = Timed_BSM_GM_Solver(model)
bsm_solver.verbose = True
bsm_eval = bsm_solver.solve(instance_file, instance_number, time)
print(bsm_eval)

Ejecutando BSM-GM con w = 1
Actualizando mejor volumen: 92.51362097627022
Ejecutando BSM-GM con w = 2
Actualizando mejor volumen: 94.18355898146936
Ejecutando BSM-GM con w = 3
Actualizando mejor volumen: 94.38503709917241
94.38503709917241

# Comparación

In [2]:
from solvers.evaluators.bs_evaluator import bs_eval
from solvers.bs.bsm_vcs import BSM_VCS_Solver
from solvers.bs.bsm_gm import BSM_GM_Solver
from solvers.bs.bsg import BSG_Solver

bsm_vcs_solver = BSM_VCS_Solver(model)
bsm_gm_solver = BSM_GM_Solver(model)
bsg_solver = BSG_Solver()

solver_list = [bsm_vcs_solver, bsm_gm_solver, bsg_solver]
instance_file = "benchmarks/BR4.txt"
num_instances = 100
w = 8

df = bs_eval(solver_list, instance_file, num_instances, w)
display(df.head())
df.mean()

,instance,Vol BSM-VCS,Time BSM-VCS,Vol BSM-GM,Time BSM-GM,Vol BSG,Time BSG
0,0,95.245118,1.953028,95.319316,3.094210,95.245118,1.344959
1,1,96.368073,2.517207,95.080147,5.751426,95.512050,2.183035
2,2,95.064843,1.399904,95.465340,3.326563,94.883252,1.173205
3,3,96.132982,3.899788,95.866329,10.594036,95.986151,3.176756
4,4,96.057089,2.785559,96.241458,7.340739,95.748378,2.130113

instance        49.500000
Vol BSM-VCS     95.408793
Time BSM-VCS     2.216117
Vol BSM-GM      95.516123
Time BSM-GM      5.668179
Vol BSG         95.216760
Time BSG         1.957766
dtype: float64

In [2]:
from solvers.evaluators.timed_evaluator import timed_eval
from solvers.timed.timed_bsm_vcs import Timed_BSM_VCS_Solver
from solvers.timed.timed_bsm_gm import Timed_BSM_GM_Solver
from solvers.timed.timed_bsg import Timed_BSG_Solver

bsm_vcs_solver = Timed_BSM_VCS_Solver(model)
bsm_gm_solver = Timed_BSM_GM_Solver(model)
bsg_solver = Timed_BSG_Solver()

solver_list = [bsm_vcs_solver]
instance_file = "benchmarks/BR4.txt"
num_instances = 30
start = 20
min_fr = 1
time = 30

df = timed_eval(solver_list, instance_file, num_instances, min_fr, time, start)
display(df.head())
df.mean()

   instance  Timed BSM-VCS
0        20      96.569820
1        21      96.572313
2        22      96.362626
3        23      95.565457
4        24      95.747889

instance         24.500000
Timed BSM-VCS    96.456756
dtype: float64