In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from models.CLPTransformer_v2 import CLPTransformer
from training import load_model

model_name = "CLPTransformer_v2_1"

model = load_model(CLPTransformer, model_name)

In [6]:
from concurrent.futures import ProcessPoolExecutor, as_completed
from solvers.greedy_model import GreedyModelSolver
from solvers.vcs import VCSSolver

instance_file = "benchmarks/BR4.txt"
w = 8

def run_instance(instance_number):
    model_solver = GreedyModelSolver(model)
    vcs_solver = VCSSolver()

    model_eval = model_solver.solve(instance_file, instance_number, w)
    vcs_eval = vcs_solver.solve(instance_file, instance_number)

    return instance_number, {'Model': model_eval, 'VCS': vcs_eval}


if __name__ == "__main__":
    results = {}

    with ProcessPoolExecutor() as executor:
        futures = [executor.submit(run_instance, i) for i in range(100)]

        for future in as_completed(futures):
            instance_number, result = future.result()
            results[instance_number] = result

    print(results)

{2: {'Model': 90.6779, 'VCS': 92.327919}, 6: {'Model': 93.6049, 'VCS': 92.563017}, 8: {'Model': 92.97609999999999, 'VCS': 94.025591}, 5: {'Model': 93.63470000000001, 'VCS': 91.870672}, 1: {'Model': 92.5566, 'VCS': 92.513621}, 9: {'Model': 90.4162, 'VCS': 93.301956}, 4: {'Model': 92.3492, 'VCS': 91.141011}, 11: {'Model': 92.3975, 'VCS': 87.225056}, 3: {'Model': 94.78410000000001, 'VCS': 92.92999}, 7: {'Model': 87.7865, 'VCS': 84.90067}, 10: {'Model': 91.7904, 'VCS': 88.84746}, 17: {'Model': 87.48010000000001, 'VCS': 77.032671}, 12: {'Model': 93.2181, 'VCS': 94.159541}, 13: {'Model': 92.3828, 'VCS': 89.929192}, 19: {'Model': 92.8635, 'VCS': 93.130983}, 15: {'Model': 93.6338, 'VCS': 91.714352}, 0: {'Model': 89.7667, 'VCS': 87.14693}, 18: {'Model': 94.3494, 'VCS': 89.296448}, 14: {'Model': 92.83590000000001, 'VCS': 91.273363}, 24: {'Model': 92.25179999999999, 'VCS': 92.374666}, 20: {'Model': 91.4828, 'VCS': 81.777277}, 21: {'Model': 93.339, 'VCS': 88.076692}, 25: {'Model': 86.78190000000001, 'VCS': 91.034769}, 26: {'Model': 89.0567, 'VCS': 92.50495}, 29: {'Model': 92.3039, 'VCS': 92.53958}, 28: {'Model': 92.7917, 'VCS': 91.291814}, 16: {'Model': 91.53099999999999, 'VCS': 91.707363}, 27: {'Model': 92.5301, 'VCS': 91.542522}, 30: {'Model': 92.2991, 'VCS': 91.613713}, 23: {'Model': 92.93679999999999, 'VCS': 85.225543}, 31: {'Model': 93.2968, 'VCS': 93.246924}, 33: {'Model': 89.4812, 'VCS': 90.95528}, 32: {'Model': 92.9126, 'VCS': 90.017408}, 22: {'Model': 89.9537, 'VCS': 91.18286}, 36: {'Model': 92.78309999999999, 'VCS': 92.707292}, 34: {'Model': 94.0608, 'VCS': 93.041614}, 35: {'Model': 93.8107, 'VCS': 92.927003}, 40: {'Model': 88.5322, 'VCS': 86.443524}, 41: {'Model': 93.3106, 'VCS': 92.947661}, 38: {'Model': 91.2633, 'VCS': 89.593272}, 44: {'Model': 93.7298, 'VCS': 92.307756}, 47: {'Model': 91.352, 'VCS': 91.851818}, 46: {'Model': 92.5874, 'VCS': 89.531985}, 48: {'Model': 84.6888, 'VCS': 90.043633}, 45: {'Model': 89.0943, 'VCS': 88.639006}, 51: {'Model': 93.38159999999999, 'VCS': 93.050893}, 49: {'Model': 90.1741, 'VCS': 92.759098}, 42: {'Model': 88.5666, 'VCS': 88.807748}, 37: {'Model': 92.48809999999999, 'VCS': 89.034006}, 50: {'Model': 93.9011, 'VCS': 92.352512}, 52: {'Model': 91.0092, 'VCS': 92.816141}, 54: {'Model': 92.6361, 'VCS': 88.531783}, 53: {'Model': 91.3309, 'VCS': 92.85306}, 55: {'Model': 95.5912, 'VCS': 93.704487}, 61: {'Model': 92.5172, 'VCS': 87.932104}, 60: {'Model': 90.32480000000001, 'VCS': 90.531718}, 43: {'Model': 91.20819999999999, 'VCS': 89.12616}, 39: {'Model': 92.7362, 'VCS': 90.452126}, 59: {'Model': 91.779, 'VCS': 92.428671}, 58: {'Model': 93.935, 'VCS': 91.614387}, 64: {'Model': 91.6346, 'VCS': 92.626706}, 56: {'Model': 93.9967, 'VCS': 89.791882}, 62: {'Model': 87.57979999999999, 'VCS': 90.392767}, 63: {'Model': 91.8536, 'VCS': 88.124031}, 66: {'Model': 91.8884, 'VCS': 90.732744}, 65: {'Model': 92.0235, 'VCS': 91.341456}, 68: {'Model': 86.4237, 'VCS': 88.547512}, 67: {'Model': 87.8848, 'VCS': 91.45403}, 57: {'Model': 90.1874, 'VCS': 90.187387}, 73: {'Model': 83.6656, 'VCS': 91.152617}, 70: {'Model': 90.6411, 'VCS': 90.981993}, 74: {'Model': 93.0763, 'VCS': 93.57175}, 71: {'Model': 91.99340000000001, 'VCS': 88.350893}, 72: {'Model': 80.9555, 'VCS': 86.656239}, 75: {'Model': 93.7667, 'VCS': 91.374049}, 76: {'Model': 92.7034, 'VCS': 94.60167}, 77: {'Model': 90.6095, 'VCS': 91.452767}, 79: {'Model': 91.647, 'VCS': 91.177496}, 80: {'Model': 93.2164, 'VCS': 93.963061}, 78: {'Model': 95.50309999999999, 'VCS': 94.831892}, 82: {'Model': 92.62209999999999, 'VCS': 94.092052}, 83: {'Model': 89.5833, 'VCS': 87.525359}, 92: {'Model': 89.2889, 'VCS': 86.444349}, 84: {'Model': 90.8527, 'VCS': 91.332523}, 88: {'Model': 91.4866, 'VCS': 90.482027}, 81: {'Model': 92.131, 'VCS': 90.457623}, 85: {'Model': 94.307, 'VCS': 92.458413}, 87: {'Model': 92.9643, 'VCS': 93.745312}, 90: {'Model': 90.5849, 'VCS': 91.801402}, 89: {'Model': 92.39450000000001, 'VCS': 90.537474}, 86: {'Model': 91.9336, 'VCS': 89.415729}, 69: {'Model': 92.3588, 'VCS': 89.690837}, 93: {'Model': 94.2003, 'VCS': 92.947076}, 94: {'Model': 89.8608, 'VCS': 91.361586}, 96: {'Model': 85.9864, 'VCS': 87.154255}, 98: {'Model': 91.1267, 'VCS': 93.798862}, 95: {'Model': 93.85289999999999, 'VCS': 92.877743}, 97: {'Model': 94.2387, 'VCS': 92.421878}, 99: {'Model': 92.1699, 'VCS': 91.091047}, 91: {'Model': 93.7736, 'VCS': 91.351536}}

In [7]:
import pandas as pd
df = pd.DataFrame(results).T.sort_index()
df['diff'] = df['Model'] - df['VCS']
print(df.mean())
df.tail(50)

Model    91.562133
VCS      90.787513
diff      0.774620
dtype: float64

      Model        VCS      diff
50  93.9011  92.352512  1.548588
51  93.3816  93.050893  0.330707
52  91.0092  92.816141 -1.806941
53  91.3309  92.853060 -1.522160
54  92.6361  88.531783  4.104317
55  95.5912  93.704487  1.886713
56  93.9967  89.791882  4.204818
57  90.1874  90.187387  0.000013
58  93.9350  91.614387  2.320613
59  91.7790  92.428671 -0.649671
60  90.3248  90.531718 -0.206918
61  92.5172  87.932104  4.585096
62  87.5798  90.392767 -2.812967
63  91.8536  88.124031  3.729569
64  91.6346  92.626706 -0.992106
65  92.0235  91.341456  0.682044
66  91.8884  90.732744  1.155656
67  87.8848  91.454030 -3.569230
68  86.4237  88.547512 -2.123812
69  92.3588  89.690837  2.667963
70  90.6411  90.981993 -0.340893
71  91.9934  88.350893  3.642507
72  80.9555  86.656239 -5.700739
73  83.6656  91.152617 -7.487017
74  93.0763  93.571750 -0.495450
75  93.7667  91.374049  2.392651
76  92.7034  94.601670 -1.898270
77  90.6095  91.452767 -0.843267
78  95.5031  94.831892  0.671208
79  91.6470  91.177496  0.469504
80  93.2164  93.963061 -0.746661
81  92.1310  90.457623  1.673377
82  92.6221  94.092052 -1.469952
83  89.5833  87.525359  2.057941
84  90.8527  91.332523 -0.479823
85  94.3070  92.458413  1.848587
86  91.9336  89.415729  2.517871
87  92.9643  93.745312 -0.781012
88  91.4866  90.482027  1.004573
89  92.3945  90.537474  1.857026
90  90.5849  91.801402 -1.216502
91  93.7736  91.351536  2.422064
92  89.2889  86.444349  2.844551
93  94.2003  92.947076  1.253224
94  89.8608  91.361586 -1.500786
95  93.8529  92.877743  0.975157
96  85.9864  87.154255 -1.167855
97  94.2387  92.421878  1.816822
98  91.1267  93.798862 -2.672162
99  92.1699  91.091047  1.078853

In [8]:
from concurrent.futures import ProcessPoolExecutor, as_completed
from solvers.bsg import BSGSolver
from solvers.bsm import BSMSolver

instance_file = "benchmarks/BR4.txt"
w = 8

def run_instance(instance_number):
    bsg_solver = BSGSolver()
    bsm_solver = BSMSolver(model)

    bsg_eval = bsg_solver.solve(instance_file, instance_number, w)
    bsm_eval = bsm_solver.solve(instance_file, instance_number, w)

    return instance_number, {'BSG': bsg_eval, 'BSM': bsm_eval}


if __name__ == "__main__":
    results = {}

    with ProcessPoolExecutor() as executor:
        futures = [executor.submit(run_instance, i) for i in range(100)]

        for future in as_completed(futures):
            instance_number, result = future.result()
            results[instance_number] = result

    print(results)

{10: {'BSG': 94.692904, 'BSM': 93.0491}, 8: {'BSG': 95.514988, 'BSM': 94.78259999999999}, 2: {'BSG': 94.883252, 'BSM': 93.7176}, 0: {'BSG': 95.245118, 'BSM': 93.3577}, 7: {'BSG': 93.013916, 'BSM': 91.2595}, 1: {'BSG': 95.51205, 'BSM': 94.5954}, 5: {'BSG': 95.215141, 'BSM': 94.0213}, 11: {'BSG': 94.208268, 'BSM': 93.6214}, 6: {'BSG': 95.464509, 'BSM': 93.8916}, 4: {'BSG': 95.748378, 'BSM': 94.6817}, 13: {'BSG': 94.465866, 'BSM': 93.0686}, 3: {'BSG': 95.986151, 'BSM': 95.2868}, 17: {'BSG': 93.123124, 'BSM': 92.0548}, 14: {'BSG': 95.415648, 'BSM': 94.6558}, 9: {'BSG': 95.310469, 'BSM': 94.541}, 16: {'BSG': 95.275314, 'BSM': 91.2367}, 20: {'BSG': 95.422714, 'BSM': 92.40559999999999}, 15: {'BSG': 95.142923, 'BSM': 94.797}, 21: {'BSG': 94.526843, 'BSM': 93.9017}, 19: {'BSG': 96.709673, 'BSM': 94.7192}, 26: {'BSG': 94.152508, 'BSM': 92.50500000000001}, 23: {'BSG': 94.593647, 'BSM': 95.07600000000001}, 18: {'BSG': 96.075188, 'BSM': 94.8629}, 22: {'BSG': 94.939039, 'BSM': 92.45689999999999}, 25: {'BSG': 95.340061, 'BSM': 94.95280000000001}, 24: {'BSG': 95.479062, 'BSM': 93.2436}, 12: {'BSG': 95.601962, 'BSM': 94.7657}, 30: {'BSG': 94.948657, 'BSM': 93.7133}, 31: {'BSG': 95.526358, 'BSM': 94.3315}, 34: {'BSG': 95.140603, 'BSM': 94.5605}, 33: {'BSG': 94.76109, 'BSM': 94.139}, 35: {'BSG': 95.98652, 'BSM': 93.94630000000001}, 28: {'BSG': 95.252383, 'BSM': 93.84169999999999}, 32: {'BSG': 96.090865, 'BSM': 95.001}, 36: {'BSG': 96.114195, 'BSM': 94.9603}, 37: {'BSG': 94.63952, 'BSM': 92.6817}, 29: {'BSG': 95.937699, 'BSM': 94.76830000000001}, 39: {'BSG': 93.850973, 'BSM': 93.9274}, 27: {'BSG': 96.274722, 'BSM': 94.6575}, 42: {'BSG': 94.59264, 'BSM': 92.9692}, 40: {'BSG': 94.470385, 'BSM': 93.3757}, 43: {'BSG': 93.335649, 'BSM': 91.6704}, 41: {'BSG': 95.665562, 'BSM': 93.0797}, 45: {'BSG': 94.589696, 'BSM': 94.5897}, 48: {'BSG': 94.16188, 'BSM': 93.2357}, 44: {'BSG': 95.692079, 'BSM': 93.9035}, 46: {'BSG': 93.682938, 'BSM': 93.3306}, 47: {'BSG': 95.896914, 'BSM': 95.2705}, 54: {'BSG': 95.623421, 'BSM': 93.038}, 52: {'BSG': 94.405566, 'BSM': 93.7477}, 56: {'BSG': 95.133664, 'BSM': 94.56649999999999}, 53: {'BSG': 95.562124, 'BSM': 93.8425}, 50: {'BSG': 96.09366, 'BSM': 94.51310000000001}, 49: {'BSG': 95.866182, 'BSM': 94.0138}, 57: {'BSG': 94.443532, 'BSM': 93.88980000000001}, 51: {'BSG': 95.393109, 'BSM': 94.4999}, 61: {'BSG': 96.343905, 'BSM': 95.5167}, 62: {'BSG': 95.647556, 'BSM': 94.9283}, 59: {'BSG': 95.095355, 'BSM': 92.8872}, 63: {'BSG': 94.417071, 'BSM': 92.9779}, 60: {'BSG': 95.997683, 'BSM': 94.622}, 38: {'BSG': 96.009418, 'BSM': 93.80380000000001}, 65: {'BSG': 96.207001, 'BSM': 94.336}, 68: {'BSG': 95.474828, 'BSM': 94.369}, 66: {'BSG': 95.179082, 'BSM': 95.222}, 58: {'BSG': 95.746121, 'BSM': 94.6886}, 67: {'BSG': 94.987873, 'BSM': 92.743}, 72: {'BSG': 93.999213, 'BSM': 92.9426}, 69: {'BSG': 94.698361, 'BSM': 93.0619}, 73: {'BSG': 93.027868, 'BSM': 87.89829999999999}, 70: {'BSG': 95.591975, 'BSM': 93.9353}, 64: {'BSG': 96.964654, 'BSM': 95.09689999999999}, 71: {'BSG': 94.434443, 'BSM': 93.0433}, 75: {'BSG': 95.056169, 'BSM': 94.2736}, 55: {'BSG': 96.57761, 'BSM': 94.6024}, 74: {'BSG': 95.018947, 'BSM': 94.1066}, 80: {'BSG': 95.48643, 'BSM': 94.015}, 79: {'BSG': 94.509661, 'BSM': 93.74249999999999}, 82: {'BSG': 96.199118, 'BSM': 94.0921}, 76: {'BSG': 96.141151, 'BSM': 94.6017}, 83: {'BSG': 93.831713, 'BSM': 92.386}, 77: {'BSG': 94.711764, 'BSM': 91.8675}, 81: {'BSG': 95.530641, 'BSM': 94.1177}, 88: {'BSG': 94.224241, 'BSM': 92.2448}, 86: {'BSG': 94.522686, 'BSM': 92.88969999999999}, 84: {'BSG': 95.762223, 'BSM': 93.0947}, 90: {'BSG': 95.490448, 'BSM': 94.6043}, 92: {'BSG': 94.358599, 'BSM': 92.9237}, 89: {'BSG': 94.65967, 'BSM': 93.14320000000001}, 91: {'BSG': 94.619769, 'BSM': 93.5539}, 87: {'BSG': 95.62828, 'BSM': 95.00110000000001}, 85: {'BSG': 96.075577, 'BSM': 94.5504}, 97: {'BSG': 95.959414, 'BSM': 94.9411}, 96: {'BSG': 94.58712, 'BSM': 91.4152}, 78: {'BSG': 97.18382, 'BSM': 95.4639}, 93: {'BSG': 96.045719, 'BSM': 94.7733}, 98: {'BSG': 96.458766, 'BSM': 94.44890000000001}, 94: {'BSG': 95.520734, 'BSM': 94.03869999999999}, 95: {'BSG': 95.450351, 'BSM': 94.7157}, 99: {'BSG': 96.051668, 'BSM': 94.3485}}

In [9]:
import pandas as pd
df = pd.DataFrame(results).T.sort_index()
df['diff'] = df['BSM'] - df['BSG']
print(df.mean())
df.tail(50)

BSG     95.216760
BSM     93.816018
diff    -1.400742
dtype: float64

          BSG      BSM      diff
50  96.093660  94.5131 -1.580560
51  95.393109  94.4999 -0.893209
52  94.405566  93.7477 -0.657866
53  95.562124  93.8425 -1.719624
54  95.623421  93.0380 -2.585421
55  96.577610  94.6024 -1.975210
56  95.133664  94.5665 -0.567164
57  94.443532  93.8898 -0.553732
58  95.746121  94.6886 -1.057521
59  95.095355  92.8872 -2.208155
60  95.997683  94.6220 -1.375683
61  96.343905  95.5167 -0.827205
62  95.647556  94.9283 -0.719256
63  94.417071  92.9779 -1.439171
64  96.964654  95.0969 -1.867754
65  96.207001  94.3360 -1.871001
66  95.179082  95.2220  0.042918
67  94.987873  92.7430 -2.244873
68  95.474828  94.3690 -1.105828
69  94.698361  93.0619 -1.636461
70  95.591975  93.9353 -1.656675
71  94.434443  93.0433 -1.391143
72  93.999213  92.9426 -1.056613
73  93.027868  87.8983 -5.129568
74  95.018947  94.1066 -0.912347
75  95.056169  94.2736 -0.782569
76  96.141151  94.6017 -1.539451
77  94.711764  91.8675 -2.844264
78  97.183820  95.4639 -1.719920
79  94.509661  93.7425 -0.767161
80  95.486430  94.0150 -1.471430
81  95.530641  94.1177 -1.412941
82  96.199118  94.0921 -2.107018
83  93.831713  92.3860 -1.445713
84  95.762223  93.0947 -2.667523
85  96.075577  94.5504 -1.525177
86  94.522686  92.8897 -1.632986
87  95.628280  95.0011 -0.627180
88  94.224241  92.2448 -1.979441
89  94.659670  93.1432 -1.516470
90  95.490448  94.6043 -0.886148
91  94.619769  93.5539 -1.065869
92  94.358599  92.9237 -1.434899
93  96.045719  94.7733 -1.272419
94  95.520734  94.0387 -1.482034
95  95.450351  94.7157 -0.734651
96  94.587120  91.4152 -3.171920
97  95.959414  94.9411 -1.018314
98  96.458766  94.4489 -2.009866
99  96.051668  94.3485 -1.703168

In [10]:
from concurrent.futures import ProcessPoolExecutor
from solvers.timed.timed_bsg import TimedBSGSolver
from solvers.timed.timed_bsm import TimedBSMSolver

instance_file = "benchmarks/BR4.txt"
instance_number = 4
time = 30

def run_bsg():
    solver = TimedBSGSolver()
    return solver.solve(instance_file, instance_number, time)

def run_bsm():
    solver = TimedBSMSolver(model)
    return solver.solve(instance_file, instance_number, time, verbose=True)

if __name__ == '__main__':
    with ProcessPoolExecutor(max_workers=2) as executor:
        future_bsg = executor.submit(run_bsg)
        future_bsm = executor.submit(run_bsm)

        timed_bsg_eval = future_bsg.result()
        timed_bsm_eval = future_bsm.result()

    print("Timed BSG:", timed_bsg_eval)
    print("Timed BSM:", timed_bsm_eval)

Ejecutando BSM con w = 1
Actualizando mejor volumen: 91.141
Ejecutando BSM con w = 2
Actualizando mejor volumen: 91.7702
Ejecutando BSM con w = 3
Actualizando mejor volumen: 93.3566
Ejecutando BSM con w = 5
Actualizando mejor volumen: 93.997
Ejecutando BSM con w = 8
Actualizando mejor volumen: 94.6817
Ejecutando BSM con w = 12
Ejecutando BSM con w = 17
Actualizando mejor volumen: 95.27980000000001
Ejecutando BSM con w = 25
Ejecutando BSM con w = 36
Timed BSG: 96.240155
Timed BSM: 95.27980000000001