In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from models.CLPTransformer_v4 import CLPTransformer
from training import load_model

model_name = "CLPTransformer_v4_CL"

model = load_model(CLPTransformer, model_name)

In [ ]:
from solvers.bsm_vcs import BSM_VCS_Solver

instance_file = "benchmarks/BR4.txt"
instance_number = 1
w = 8

bsm_solver = BSM_VCS_Solver(model, w)
bsm_eval = bsm_solver.solve(instance_file, instance_number)
print(bsm_eval)

TypeError: BSM_VCS_Solver.solve() takes 3 positional arguments but 4 were given

In [2]:
from solvers.bsm_gm import BSM_GM_Solver

instance_file = "benchmarks/BR4.txt"
instance_number = 1
w = 2

bsm_solver = BSM_GM_Solver(model)
bsm_eval = bsm_solver.solve(instance_file, instance_number, w)
print(bsm_eval)

94.18355898146936

In [10]:
from solvers.bsg import BSGSolver

instance_file = "benchmarks/BR4.txt"
instance_number = 1
w = 8

bsg_solver = BSGSolver()
bsg_eval = bsg_solver.solve(instance_file, instance_number, w)
print(bsg_eval)

95.51205

In [ ]:
from solvers.bsm_gm import BSMSolver

instance_file = "benchmarks/BR4.txt"
w = 2

evals = []
for instance_number in range(100):
    bsm_solver = BSMSolver(model)
    bsm_eval = bsm_solver.solve(instance_file, instance_number, w)
    evals.append(bsm_eval)
    
print(evals)
print(sum(evals) / len(evals))

KeyboardInterrupt:

In [4]:
from solvers.bsg import BSGSolver

instance_file = "benchmarks/BR4.txt"
w = 8

evals = []
for instance_number in range(100):
    bsg_solver = BSGSolver()
    bsg_eval = bsg_solver.solve(instance_file, instance_number, w)
    evals.append(bsg_eval)
    
print(evals)
print(sum(evals) / len(evals))

[95.245118, 95.51205, 94.883252, 95.986151, 95.748378, 95.215141, 95.464509, 93.013916, 95.514988, 95.310469, 94.692904, 94.208268, 95.601962, 94.465866, 95.415648, 95.142923, 95.275314, 93.123124, 96.075188, 96.709673, 95.422714, 94.526843, 94.939039, 94.593647, 95.479062, 95.340061, 94.152508, 96.274722, 95.252383, 95.937699, 94.948657, 95.526358, 96.090865, 94.76109, 95.140603, 95.98652, 96.114195, 94.63952, 96.009418, 93.850973, 94.470385, 95.665562, 94.59264, 93.335649, 95.692079, 94.589696, 93.682938, 95.896914, 94.16188, 95.866182, 96.09366, 95.393109, 94.405566, 95.562124, 95.623421, 96.57761, 95.133664, 94.443532, 95.746121, 95.095355, 95.997683, 96.343905, 95.647556, 94.417071, 96.964654, 96.207001, 95.179082, 94.987873, 95.474828, 94.698361, 95.591975, 94.434443, 93.999213, 93.027868, 95.018947, 95.056169, 96.141151, 94.711764, 97.18382, 94.509661, 95.48643, 95.530641, 96.199118, 93.831713, 95.762223, 96.075577, 94.522686, 95.62828, 94.224241, 94.65967, 95.490448, 94.619769, 94.358599, 96.045719, 95.520734, 95.450351, 94.58712, 95.959414, 96.458766, 96.051668]
95.21675998

In [6]:
from solvers.bsg import BSGSolver

instance_file = "benchmarks/BR4.txt"
instance_number = 1
w = 16

bsg_solver = BSGSolver()
bsg_eval = bsg_solver.solve(instance_file, instance_number, w)
print(bsg_eval)

96.497104

In [ ]:
from concurrent.futures import ThreadPoolExecutor, as_completed
from solvers.sequential.greedy import GreedyModelSolver
from solvers.vcs import VCSSolver

instance_file = "benchmarks/BR7.txt"
w = 8

def run_instance(instance_number):
    model_solver = GreedyModelSolver(model)
    vcs_solver = VCSSolver()

    model_eval = model_solver.solve(instance_file, instance_number, w)
    vcs_eval = vcs_solver.solve(instance_file, instance_number)

    return instance_number, {'Model': model_eval, 'VCS': vcs_eval}


if __name__ == "__main__":
    results = {}

    with ThreadPoolExecutor(max_workers=32) as executor:
        futures = [executor.submit(run_instance, i) for i in range(10)]

        for future in as_completed(futures):
            instance_number, result = future.result()
            results[instance_number] = result

    print(results)

{2: {'Model': 89.5624, 'VCS': 91.002146}, 4: {'Model': 92.548, 'VCS': 92.35321}, 7: {'Model': 89.34609999999999, 'VCS': 90.314361}, 0: {'Model': 93.76400000000001, 'VCS': 93.197415}, 1: {'Model': 90.4269, 'VCS': 91.89574}, 8: {'Model': 91.79469999999999, 'VCS': 91.370659}, 9: {'Model': 92.95219999999999, 'VCS': 90.343088}, 5: {'Model': 91.3886, 'VCS': 92.497685}, 6: {'Model': 92.0765, 'VCS': 91.984535}, 3: {'Model': 91.6176, 'VCS': 93.381635}}

In [ ]:
import pandas as pd
df = pd.DataFrame(results).T.sort_index()
df['diff'] = df['Model'] - df['VCS']
print(df.mean())

Model    91.547700
VCS      91.834047
diff     -0.286347
dtype: float64

In [ ]:
from concurrent.futures import ProcessPoolExecutor
from solvers.bsg import BSGSolver
from solvers.bsm_gm import BSMSolver

instance_file = "benchmarks/BR4.txt"
num_instances = 20
w = 8

def run_bsg(instance_number):
    solver = BSGSolver()
    return solver.solve(instance_file, instance_number, w)

def run_bsm(instance_number):
    solver = BSMSolver(model)
    return solver.solve(instance_file, instance_number, w)

if __name__ == '__main__':
    results = {}
    for i in range(num_instances):
        print("Resolviendo instancia", i+1)
        with ProcessPoolExecutor(max_workers=2) as executor:
            future_bsg = executor.submit(run_bsg, instance_number=i)
            future_bsm = executor.submit(run_bsm, instance_number=i)

            bsg_eval = future_bsg.result()
            bsm_eval = future_bsm.result()
            
            results[i] = {
                'BSG': bsg_eval,
                'BSM': bsm_eval
            }

Resolviendo instancia 1
['0.924979', '0.871469', '0.926189', '0.933577', '0.906179', '0.883201', '0.884223', '0.884389', '8']
['0.871469', '0.900795', '0.900795', '0.914847', '0.889195', '0.894189', '0.899556', '0.899556', '0.929441', '0.929441', '0.883201', '0.91488', '0.903869', '0.892479', '0.891385', '0.873011', '0.884223', '0.899541', '0.885271', '0.908338', '0.892572', '0.885935', '0.891385', '0.909822', '0.903768', '0.884389', '0.924979', '0.903768', '0.923143', '0.873606', '0.907948', '0.900426', '0.906179', '0.89906', '0.891941', '0.887401', '0.911951', '0.895584', '0.89833', '0.893305', '0.924979', '0.871469', '0.870298', '0.895584', '0.920129', '0.916634', '0.911875', '0.91694', '0.891941', '0.908085', '0.926189', '0.908021', '0.89026', '0.930625', '0.901164', '0.903768', '0.933577', '0.901967', '0.865357', '0.891373', '0.909475', '0.89833', '0.933637', '0.918783', '8']
['0.895584', '0.892981', '0.883129', '0.903768', '0.865357', '0.871763', '0.903768', '0.869634', '0.870298', '0.870298', '0.909919', '0.89389', '0.894146', '0.889935', '0.909601', '0.889935', '0.891385', '0.903768', '0.871469', '0.903768', '0.903768', '0.903768', '0.877929', '0.899882', '0.873011', '0.854666', '0.846483', '0.854666', '0.876023', '0.846483', '0.846483', '0.846483', '0.873606', '0.873606', '0.886001', '0.873606', '0.886001', '0.877518', '0.911111', '0.877518', '0.883201', '0.883201', '0.883201', '0.883201', '0.883201', '0.883201', '0.883201', '0.883201', '0.884223', '0.884223', '0.877763', '0.877763', '0.89416', '0.904304', '0.904304', '0.904304', '0.884389', '0.903768', '0.903768', '0.903768', '0.90561', '0.884389', '0.890147', '0.903768', '8']
['0.846483', '0.846483', '0.846483', '0.846483', '0.876023', '0.854666', '0.846483', '0.854666', '0.846483', '0.846483', '0.873011', '0.846483', '0.890147', '0.908069', '0.908069', '0.891873', '0.915188', '0.914192', '0.865357', '0.907093', '0.910285', '0.920948', '0.869634', '0.869634', '0.9137', '0.891608', '0.876699', '0.904963', '0.870298', '0.870298', '0.874958', '0.870298', '0.871363', '0.870298', '0.870298', '0.874126', '0.871469', '0.871469', '0.871469', '0.883201', '0.871469', '0.883201', '0.871469', '0.871469', '0.871763', '0.86358', '0.883141', '0.866774', '0.873893', '0.873893', '0.877817', '0.905562', '0.86285', '0.873011', '0.86934', '0.86934', '0.867839', '0.846483', '0.876023', '0.867839', '8']
['0.846483', '0.846483', '0.846483', '0.86285', '0.86285', '0.846483', '0.86072', '0.86285', '0.854666', '0.846483', '0.846483', '0.846483', '0.846483', '0.846483', '0.846483', '0.851654', '0.86285', '0.86285', '0.86285', '0.86285', '0.86358', '0.856461', '0.856461', '0.901052', '0.86358', '0.90266', '0.856461', '0.877817', '0.865357', '0.890147', '0.882194', '0.87936', '0.891373', '0.892981', '0.892981', '0.882194', '0.866774', '0.872828', '0.866774', '0.862515', '0.911604', '0.862515', '0.866774', '0.911604', '0.867839', '0.846483', '0.86285', '0.86285', '0.893231', '0.846483', '0.86285', '0.86285', '0.86934', '0.846483', '0.846483', '0.86072', '0.869563', '0.86072', '0.846483', '0.846483', '8']
['0.846483', '0.846483', '0.846483', '0.846483', '0.880565', '0.880565', '0.851654', '0.846483', '0.869563', '0.86072', '0.846483', '0.86072', '0.854666', '0.854666', '0.854666', '0.846483', '0.846483', '0.86285', '0.854666', '0.854666', '0.854666', '0.854666', '0.856461', '0.856461', '0.856461', '0.855396', '0.856461', '0.855396', '0.856461', '0.856461', '0.86072', '0.846483', '0.86934', '0.86934', '0.86934', '0.86934', '0.86285', '0.862515', '0.862515', '0.848278', '0.857526', '0.86571', '0.862515', '0.862515', '0.862515', '0.86285', '0.86285', '0.86285', '0.86285', '0.86358', '0.856461', '0.869634', '0.877817', '0.86358', '0.856461', '0.877817', '0.86358', '8']
['0.846483', '0.896902', '0.86285', '0.86285', '0.86285', '0.86285', '0.86285', '0.86285', '0.848278', '0.886001', '0.906457', '0.900817', '0.856461', '0.877817', '0.891325', '0.899221', '0.851654', '0.851654', '0.851654', '0.851654', '0.854666', '0.854666', '0.86285', '0.848278', '0.855396', '0.901052', '0.890265', '0.877817', '0.877817', '0.877578', '0.856461', '0.856461', '0.889973', '0.856461', '0.879186', '0.890808', '0.901291', '0.864645', '0.877817', '0.874958', '0.857526', '0.862515', '0.919848', '0.907834', '0.907834', '0.919848', '0.850407', '0.86072', '0.86072', '0.86072', '0.86072', '0.86072', '0.86072', '8']
['0.846483', '0.846483', '0.846483', '0.846483', '0.846483', '0.846483', '0.846483', '0.881012', '0.848278', '0.877817', '0.890647', '0.876741', '0.88767', '0.856461', '0.871303', '0.850407', '0.886001', '0.892634', '0.903421', '0.88731', '0.888722', '0.903677', '0.877805', '0.851654', '0.851654', '0.854666', '0.86285', '0.846483', '0.846483', '0.864633', '0.846483', '0.866762', '0.879217', '0.855396', '0.889973', '0.891873', '0.901291', '0.86358', '0.877817', '0.876741', '0.89295', '0.856461', '0.856461', '0.856461', '0.856461', '0.857526', '0.886001', '0.898274', '0.932243', '0.888978', '0.906627', '0.926919', '0.899509', '8']
['0.906151', '0.846483', '0.86072', '0.879653', '0.906151', '0.868486', '0.86072', '0.86072', '0.848278', '0.848278', '0.848278', '0.848278', '0.856461', '0.848278', '0.848278', '0.848278', '0.850407', '0.850407', '0.850407', '0.842224', '0.841159', '0.841159', '0.841159', '0.850407', '0.851654', '0.851654', '0.846483', '0.854666', '0.899032', '0.877929', '0.854666', '0.854666', '0.899032', '0.87667', '0.87021', '0.855396', '0.855396', '0.855396', '0.862515', '0.877817', '0.877817', '0.855396', '0.856461', '0.856461', '0.855396', '0.857526', '0.86571', '0.855396', '0.858591', '0.848278', '0.856461', '0.848278', '8']
['0.841159', '0.842224', '0.842224', '0.842224', '0.842224', '0.842224', '0.883141', '0.846483', '0.855791', '0.86285', '0.860809', '0.883141', '0.860274', '0.86508', '0.848278', '0.856461', '0.855396', '0.855396', '0.856461', '0.848278', '0.848278', '0.848278', '0.850407', '0.841159', '0.841159', '0.83404', '0.851654', '0.873193', '0.876205', '0.879653', '0.854308', '0.848266', '0.834435', '0.854666', '0.854666', '0.846483', '0.861785', '0.879217', '0.86501', '0.867839', '0.854666', '0.861785', '0.855396', '0.848278', '0.866774', '8']
['0.83404', '0.83404', '0.834435', '0.83337', '0.834435', '0.830176', '0.830176', '0.830176', '0.862038', '0.834435', '0.841159', '0.842224', '0.86358', '0.86358', '0.86358', '0.849342', '0.86358', '0.86358', '0.86358', '0.861785', '0.846483', '0.861785', '0.846483', '0.850366', '0.846107', '0.851654', '0.846483', '0.849931', '0.848266', '0.871134', '0.841147', '0.867839', '0.869563', '0.855102', '0.874735', '0.848278', '0.850407', '0.858591', '0.855396', '0.855396', '0.883141', '0.855396', '0.858591', '0.850407', '0.850407', '8']
['0.830176', '0.83337', '0.83404', '0.855396', '0.855396', '0.855396', '0.841159', '0.855396', '0.855396', '0.855396', '0.834435', '0.841147', '0.841159', '0.862515', '0.862515', '0.862515', '0.848278', '0.862515', '0.862515', '0.862515', '0.842224', '0.849342', '0.842224', '0.842224', '0.842224', '0.846107', '0.846107', '0.839647', '0.839647', '0.846543', '0.846543', '0.830176', '0.834506', '8']
['0.830176', '0.830176', '0.830176', '0.830176', '0.830176', '0.830176', '0.83337', '0.847383', '0.83337', '0.847383', '0.830387', '0.847383', '0.847383', '0.830387', '0.83404', '0.83404', '0.83404', '0.834435', '0.83337', '0.83124', '0.834435', '0.83124', '0.849931', '0.83124', '0.834028', '0.834506', '0.83623', '0.834506', '0.828046', '0.83623', '0.828046', '0.839647', '0.839647', '0.839647', '0.839647', '0.861785', '0.841147', '0.864574', '0.854666', '0.845789', '0.845789', '0.845789', '0.845789', '0.841159', '0.83404', '0.850407', '0.842224', '0.842224', '0.850407', '8']
['0.828046', '0.83623', '0.828046', '0.83623', '0.830176', '0.830176', '0.830176', '0.830176', '0.830387', '0.830387', '0.830387', '0.831452', '0.830387', '0.831452', '0.842242', '0.835123', '0.83124', '0.842871', '0.83124', '0.841177', '0.841177', '0.841177', '0.8392', '0.8392', '0.83337', '0.847383', '0.83337', '0.847383', '0.830387', '0.847383', '0.847383', '0.830387', '0.834028', '0.843471', '0.842212', '0.843471', '0.834028', '0.834028', '0.834028', '0.834028', '0.83404', '0.834435', '0.844595', '0.834435', '0.844371', '0.844371', '0.844371', '0.844371', '0.844371', '7']
['0.828046', '0.828046', '0.824598', '0.826322', '0.830176', '0.830176', '0.830387', '0.830387', '0.830387', '0.831452', '0.830387', '0.831452', '0.842242', '0.835123', '0.83124', '0.83124', '0.83337', '0.840053', '0.832305', '0.840053', '0.840053', '0.839394', '0.831452', '0.831452', '0.83337', '0.834435', '0.83337', '0.834435', '0.838106', '0.837447', '0.83337', '0.830987', '0.834028', '0.834028', '0.834028', '0.842212', '0.843936', '0.843936', '0.842212', '0.842212', '6']
['0.826322', '0.824598', '0.828046', '0.826322', '0.830176', '0.830176', '0.826728', '0.828452', '0.830387', '0.830387', '0.83124', '0.832305', '0.83124', '0.832305', '0.835976', '0.835317', '0.83337', '0.828858', '0.831452', '4']
['0.828452', '0.826728', '0.828858', '0.830987', '0.828858', '0.829922', '0.82754', '0.828199', '0.830176', '0.828452', '0.830387', '0.830387', '0.831452', '0.829728', '4']
['0.829263', '0.828199', '0.82754', '0.828858', '0.829922', '0.828199', '0.829728', '0.830987', '0.829922', '0.829263', '0']
Resolviendo instancia 2
['0.898571', '0.933943', '0.900449', '0.913558', '0.925566', '0.925982', '0.925495', '0.925495', '7']
['0.898571', '0.898571', '0.898571', '0.90568', '0.898571', '0.928735', '0.925688', '0.925688', '0.916275', '0.909705', '0.906825', '0.909212', '0.909849', '0.906825', '0.900449', '0.900449', '0.913558', '0.913558', '0.89234', '0.898288', '0.898288', '0.89234', '0.890034', '0.898571', '0.925495', '0.925495', '0.923343', '0.898571', '0.907534', '0.907534', '0.920223', '0.912875', '0.925566', '0.925566', '0.925566', '0.925566', '0.925566', '0.943569', '0.925566', '0.925566', '0.925982', '0.925982', '0.923721', '0.898571', '0.904008', '0.904008', '0.920223', '0.907534', '0.933943', '0.925866', '0.925866', '0.925866', '0.925866', '0.927952', '0.898571', '0.925866', '8']
['0.887869', '0.890034', '0.893873', '0.890175', '0.881921', '0.898429', '0.899631', '0.887869', '0.885995', '0.89234', '0.908074', '0.917206', '0.918424', '0.926265', '0.909518', '0.931463', '0.887869', '0.898288', '0.893873', '0.890175', '0.898571', '0.898429', '0.896804', '0.871078', '0.898571', '0.929047', '0.898571', '0.889164', '0.889164', '0.889164', '0.889164', '0.898571', '0.878462', '0.900449', '0.913638', '0.864563', '0.89941', '0.894711', '0.881921', '0.889468', '0.904008', '0.920017', '0.910017', '0.920017', '0.909332', '0.891156', '0.910411', '0.910411', '0.898571', '0.90568', '0.90568', '0.921931', '0.929743', '0.908076', '0.929743', '0.939608', '0.890175', '0.890175', '0.890175', '0.890175', '0.890175', '0.906825', '0.906825', '0.906825', '8']
['0.864563', '0.882035', '0.864705', '0.881496', '0.898146', '0.848621', '0.889609', '0.889751', '0.871078', '0.905248', '0.888577', '0.921604', '0.906608', '0.899055', '0.895178', '0.906825', '0.881779', '0.906684', '0.881921', '0.878462', '0.889627', '0.898571', '0.902015', '0.918634', '0.890175', '0.881921', '0.885723', '0.848621', '0.889171', '0.898732', '0.898732', '0.898732', '0.885995', '0.903165', '0.939876', '0.911676', '0.91435', '0.938816', '0.907288', '0.933204', '0.887869', '0.904378', '0.872524', '0.895423', '0.871078', '0.905824', '0.905824', '0.899678', '0.889164', '0.906825', '0.898571', '0.897276', '0.897276', '0.897276', '0.910379', '0.881779', '0.881779', '0.881921', '0.889468', '0.873525', '0.890175', '0.864988', '0.881921', '0.912687', '8']
['0.848621', '0.874071', '0.886923', '0.881921', '0.873384', '0.898571', '0.898571', '0.898571', '0.864563', '0.889609', '0.906259', '0.899812', '0.872959', '0.872818', '0.872818', '0.872818', '0.864705', '0.876315', '0.873101', '0.873101', '0.873101', '0.856592', '0.864846', '0.869562', '0.864988', '0.864988', '0.865129', '0.881921', '0.898571', '0.865129', '0.881921', '0.915079', '0.871078', '0.854428', '0.912774', '0.872524', '0.871078', '0.921604', '0.871948', '0.906636', '0.887869', '0.899735', '0.888598', '0.889033', '0.872524', '0.889609', '0.904378', '0.906249', '0.873525', '0.848479', '0.898429', '0.898288', '0.890034', '0.856734', '0.898288', '0.890034', '0.878462', '0.906006', '0.909212', '0.893585', '0.914822', '0.91282', '0.912272', '0.905476', '8']
['0.848479', '0.840225', '0.848479', '0.840225', '0.856734', '0.840225', '0.848479', '0.873242', '0.848621', '0.848621', '0.881638', '0.848621', '0.893087', '0.893087', '0.893087', '0.871274', '0.899055', '0.900771', '0.890638', '0.907173', '0.854428', '0.908234', '0.854428', '0.92682', '0.856592', '0.856592', '0.864988', '0.898288', '0.864988', '0.856592', '0.881496', '0.881638', '0.856734', '0.856734', '0.848479', '0.848479', '0.864988', '0.864988', '0.873242', '0.905397', '0.864563', '0.872818', '0.884909', '0.881213', '0.889468', '0.872818', '0.872818', '0.872818', '0.864705', '0.848338', '0.890034', '0.890034', '0.890034', '0.890034', '0.864988', '0.864705', '0.864846', '0.864988', '0.881638', '0.864988', '0.864846', '0.881638', '0.898288', '0.881213', '8']
['0.840225', '0.831971', '0.840225', '0.840225', '0.840225', '0.848479', '0.831971', '0.848479', '0.848338', '0.848338', '0.848338', '0.873384', '0.864705', '0.864705', '0.873384', '0.873384', '0.848479', '0.848479', '0.848479', '0.848479', '0.848479', '0.848479', '0.848479', '0.848479', '0.881921', '0.881921', '0.848621', '0.899118', '0.848621', '0.881921', '0.848621', '0.904291', '0.854428', '0.889033', '0.854428', '0.889033', '0.904378', '0.904378', '0.904378', '0.904378', '0.856592', '0.856592', '0.856592', '0.856592', '0.856592', '0.856592', '0.856592', '0.856592', '0.856734', '0.856875', '0.873525', '0.865271', '0.840225', '0.856734', '0.856734', '0.856734', '0.864563', '0.864563', '0.864563', '0.864563', '0.908668', '0.872818', '0.908668', '0.872818', '8']
['0.831971', '0.889892', '0.889892', '0.856734', '0.890034', '0.881779', '0.881779', '0.881638', '0.840225', '0.890175', '0.890175', '0.881779', '0.890175', '0.873242', '0.890175', '0.873242', '0.848338', '0.848338', '0.848338', '0.848338', '0.848338', '0.848338', '0.848338', '0.848338', '0.848479', '0.898288', '0.898005', '0.873384', '0.890034', '0.898288', '0.898288', '0.898146', '0.848621', '0.848621', '0.848621', '0.848621', '0.848621', '0.848621', '0.848621', '0.854863', '0.854428', '0.889033', '0.884341', '0.888163', '0.889033', '0.887728', '0.854428', '0.856451', '0.856451', '0.864846', '0.856592', '0.839801', '0.856451', '0.848196', '0.839801', '0.856734', '0.873242', '0.873242', '0.881779', '0.881638', '0.881638', '0.881638', '0.873384', '8']
['0.831971', '0.856875', '0.848479', '0.865129', '0.881638', '0.864988', '0.856734', '0.856875', '0.839801', '0.839801', '0.839801', '0.839801', '0.839801', '0.839801', '0.839801', '0.839801', '0.840225', '0.865271', '0.865271', '0.865271', '0.865271', '0.865271', '0.865271', '0.865271', '0.839801', '0.848196', '0.839801', '0.848196', '0.839801', '0.848196', '0.848196', '0.848196', '0.873242', '0.881779', '0.848338', '0.831264', '0.873525', '0.864988', '0.864563', '0.865129', '0.881779', '0.848479', '0.873525', '0.873525', '0.873525', '0.873525', '0.881779', '0.881779', '0.848621', '0.848621', '0.896717', '0.899118', '0.848621', '0.871219', '0.896804', '0.887869', '0.854428', '0.854428', '0.854428', '0.854428', '0.854428', '8']
['0.831264', '0.831264', '0.831264', '0.831264', '0.831264', '0.831264', '0.831264', '0.831264', '0.831971', '0.848479', '0.840225', '0.831971', '0.848479', '0.840225', '0.848479', '0.848479', '0.839801', '0.839801', '0.831546', '0.831546', '0.848479', '0.848479', '0.856875', '0.840225', '0.840225', '0.840225', '0.848479', '0.848479', '0.848196', '0.856592', '0.839801', '0.856592', '0.839801', '0.848055', '0.839801', '0.848338', '0.848338', '0.848338', '0.848338', '0.848338', '0.848338', '0.848338', '0.848338', '0.848479', '0.873384', '0.864988', '0.864988', '0.856734', '0.856734', '0.856734', '0.864988', '0.856875', '0.898588', '0.898588', '0.848621', '0.904291', '0.904291', '0.873384', '0.900839', '8']
['0.831264', '0.831264', '0.831264', '0.831264', '0.831546', '0.839942', '0.839942', '0.831546', '0.848196', '0.831971', '0.831971', '0.840225', '0.848479', '0.848479', '0.840225', '0.840225', '0.848479', '0.839801', '0.839801', '0.839801', '0.839801', '0.839801', '0.840225', '0.865271', '0.865271', '0.865271', '0.840225', '0.840225', '0.865271', '0.865271', '0.848055', '0.848055', '0.848055', '0.848196', '0.848196', '0.848196', '0.848196', '0.848196', '0.848196', '0.848196', '0.848196', '0.848338', '0.848338', '0.848338', '0.848338', '0.848338', '0.848338', '0.848338', '0.848338', '8']
['0.831264', '0.822868', '0.831264', '0.822868', '0.822868', '0.822868', '0.831264', '0.822868', '0.831546', '0.831971', '0.848479', '0.840225', '0.856734', '0.831971', '0.856734', '0.856734', '0.856734', '0.839801', '0.856592', '0.839942', '0.865271', '0.840225', '0.873525', '0.840225', '0.840225', '0.831971', '0.831971', '0.856734', '0.848055', '0.848196', '8']
['0.822868', '0.822868', '0.831264', '0.831264', '0.831546', '0.831546', '0.814896', '0.831546', '0.814896', '0.822868', '0.831546', '0.806501', '0.831971', '0.831971', '0.831971', '0.848621', '0.831971', '0.848621', '0.848621', '0.848621', '0.839801', '0.839942', '0.856168', '0.831546', '0.831546', '0.815038', '0.806501', '0.839942', '0.822868', '0.840225', '0.840225', '0.840225', '0.848479', '0.848621', '0.848621', '0.848621', '0.848479', '0.831829', '0.848055', '0.848055', '0.848338', '0.848055', '0.848055', '0.848338', '0.839942', '8']
['0.815038', '0.815038', '0.806501', '0.806501', '0.814896', '0.814896', '0.814896', '0.814896', '0.823434', '0.823434', '0.815038', '0.815038', '0.839659', '0.839659', '0.822868', '0.822868', '0.831264', '0.822868', '0.831264', '0.822868', '0.822868', '0.822868', '0.814614', '0.831546', '0.839942', '0.831546', '0.831829', '0.831829', '0.856592', '0.864563', '0.831546', '0.856592', '0.847913', '0.840084', '0.848621', '0.831971', '0.848621', '0.848621', '0.848621', '0.848621', '0.848621', '0.848621', '6']
['0.806501', '0.823151', '0.806501', '0.831546', '0.814896', '0.814896', '0.822868', '0.823434', '0.815038', '0.815038', '0.831264', '0.831546', '0.831546', '0.831546', '0.831688', '0.840225', '4']
['0.806501', '0.806501', '0.814896', '0.823151', '0.806501', '0.823151', '0.823151', '0.806501', '0.806642', '0.814896', '0.806501', '0.831546', '0.831688', '0.831546', '0.831546', '0.831688', '0.831546', '4']
['0.806501', '0.806501', '0.814896', '0.823151', '0.806501', '0.831546', '0.831546', '1']
['0.823151', '0.823151', '0']
Resolviendo instancia 3
['0.923923', '0.923279', '0.897273', '0.868815', '0.893394', '0.920677', '0.89611', '0.915933', '8']
['0.921158', '0.904056', '0.898007', '0.932731', '0.87991', '0.916806', '0.909159', '0.90559', '0.914026', '0.914026', '0.921365', '0.937176', '0.901996', '0.919317', '0.920425', '0.925816', '0.89611', '0.923923', '0.920798', '0.901397', '0.912939', '0.904848', '0.874132', '0.919323', '0.897273', '0.897273', '0.924449', '0.9217', '0.905021', '0.914321', '0.918433', '0.890222', '0.915933', '0.904114', '0.897724', '0.900491', '0.898801', '0.887832', '0.903128', '0.864128', '0.920677', '0.923518', '0.91731', '0.916868', '0.897273', '0.931007', '0.912224', '0.905751', '0.923279', '0.920677', '0.923923', '0.934558', '0.911986', '0.93265', '0.890137', '0.909166', '0.923923', '0.923518', '0.929748', '0.93071', '0.926814', '0.936387', '0.890137', '0.914426', '8']

In [ ]:
import pandas as pd
df = pd.DataFrame(results).T.sort_index()
df['diff'] = df['BSM'] - df['BSG']
print(df.mean())
df.tail(50)

BSG     95.130242
BSM     93.917175
diff    -1.213067
dtype: float64

          BSG      BSM      diff
0   95.245118  93.3637 -1.881418
1   95.512050  94.3569 -1.155150
2   94.883252  93.7176 -1.165652
3   95.986151  94.6431 -1.343051
4   95.748378  94.7641 -0.984278
5   95.215141  94.2830 -0.932141
6   95.464509  94.1374 -1.327109
7   93.013916  91.2666 -1.747316
8   95.514988  94.7826 -0.732388
9   95.310469  95.2260 -0.084469
10  94.692904  93.9147 -0.778204
11  94.208268  93.7273 -0.480968
12  95.601962  95.4765 -0.125462
13  94.465866  93.2480 -1.217866
14  95.415648  95.2044 -0.211248
15  95.142923  94.0819 -1.061023
16  95.275314  90.6318 -4.643514
17  93.123124  91.8295 -1.293624
18  96.075188  94.9692 -1.105988
19  96.709673  94.7192 -1.990473

In [ ]:
from concurrent.futures import ProcessPoolExecutor
from solvers.timed.timed_bsg import TimedBSGSolver
from solvers.timed.timed_bsm import TimedBSMSolver

instance_file = "benchmarks/BR4.txt"
instance_number = 1
time = 30

def run_bsg():
    solver = TimedBSGSolver()
    return solver.solve(instance_file, instance_number, time)

def run_bsm():
    solver = TimedBSMSolver(model)
    return solver.solve(instance_file, instance_number, time, verbose=True)

if __name__ == '__main__':
    with ProcessPoolExecutor(max_workers=2) as executor:
        future_bsg = executor.submit(run_bsg)
        future_bsm = executor.submit(run_bsm)

        timed_bsg_eval = future_bsg.result()
        timed_bsm_eval = future_bsm.result()

    print("Timed BSG:", timed_bsg_eval)
    print("Timed BSM:", timed_bsm_eval)

Ejecutando BSM con w = 1
Actualizando mejor volumen: 92.5136
Ejecutando BSM con w = 2
Actualizando mejor volumen: 93.3528
Ejecutando BSM con w = 3
Ejecutando BSM con w = 5
Ejecutando BSM con w = 8
Actualizando mejor volumen: 95.0251
Ejecutando BSM con w = 12
Ejecutando BSM con w = 17
Ejecutando BSM con w = 25
Ejecutando BSM con w = 36
Timed BSG: 96.497104
Timed BSM: 95.0251

In [ ]:
from concurrent.futures import ProcessPoolExecutor
from solvers.timed.timed_bsg import TimedBSGSolver
from solvers.timed.timed_bsm import TimedBSMSolver

instance_file = "benchmarks/BR4.txt"
num_instances = 20
time = 30

def run_bsg(instance_number):
    solver = TimedBSGSolver()
    return solver.solve(instance_file, instance_number, time)

def run_bsm(instance_number):
    solver = TimedBSMSolver(model)
    return solver.solve(instance_file, instance_number, time)

if __name__ == '__main__':
    results = {}
    for i in range(num_instances):
        print("Resolviendo instancia", i+1)
        with ProcessPoolExecutor(max_workers=2) as executor:
            future_bsg = executor.submit(run_bsg, instance_number=i)
            future_bsm = executor.submit(run_bsm, instance_number=i)

            timed_bsg_eval = future_bsg.result()
            timed_bsm_eval = future_bsm.result()
            
            results[i] = {
                'Timed BSG': timed_bsg_eval,
                'Timed BSM': timed_bsm_eval
            }

Resolviendo instancia 0
Resolviendo instancia 1
Resolviendo instancia 2
Resolviendo instancia 3
Resolviendo instancia 4
Resolviendo instancia 5
Resolviendo instancia 6
Resolviendo instancia 7
Resolviendo instancia 8
Resolviendo instancia 9
Resolviendo instancia 10
Resolviendo instancia 11
Resolviendo instancia 12
Resolviendo instancia 13
Resolviendo instancia 14
Resolviendo instancia 15
Resolviendo instancia 16
Resolviendo instancia 17
Resolviendo instancia 18
Resolviendo instancia 19

In [ ]:
import pandas as pd
df = pd.DataFrame(results).T.sort_index()
df['diff'] = df['Timed BSM'] - df['Timed BSG']
print(df.mean())

Timed BSG    95.901950
Timed BSM    94.602595
diff         -1.299355
dtype: float64

In [ ]:
df

    Timed BSG  Timed BSM      diff
0   95.245118    93.3577 -1.887418
1   96.497104    95.2011 -1.296004
2   95.891085    94.1940 -1.697085
3   96.287849    95.2073 -1.080549
4   96.240155    94.6353 -1.604855
5   95.960560    94.8463 -1.114260
6   96.195632    94.6429 -1.552732
7   94.634778    93.6119 -1.022878
8   96.351250    94.8163 -1.534950
9   95.832716    95.2260 -0.606716
10  95.491007    93.9320 -1.559007
11  94.379038    95.0541  0.675062
12  96.827122    95.2927 -1.534422
13  95.818000    94.2618 -1.556200
14  96.403983    95.9164 -0.487583
15  95.777218    94.5166 -1.260618
16  95.275314    93.0398 -2.235514
17  95.281011    93.1228 -2.158211
18  96.940383    95.4698 -1.470583
19  96.709673    95.7071 -1.002573

In [ ]:
from concurrent.futures import ProcessPoolExecutor
from solvers.bsg import BSGSolver
from solvers.bsm_gm import BSMSolver

instance_file = "benchmarks/BR4.txt"
instance_number = 0
w = 42

solver = BSGSolver()
bsg_sol = solver.solve(instance_file, instance_number, w)
print(bsg_sol)

95.219056

In [ ]:
from importlib import reload
import solvers.bsm_gm
reload(solvers.bsm_gm)

In [ ]:
from concurrent.futures import ProcessPoolExecutor
from solvers.bsg import BSGSolver
from solvers.bsm_gm import BSMSolver

instance_file = "benchmarks/BR4.txt"
instance_number = 0
w = 42

solver = BSMSolver(model)
bsm_sol = solver.solve(instance_file, instance_number, w)
print(bsm_sol)

1
37
42
42
42
42
42
42
18
9
317
92.9588